version: 2
jobs:
  build:
    docker:
      # Image to run Ruby 1.9.3 with the latest bundler, RubyGems, etc.
      - image: corgibytes/ruby-1.9.3:1.0.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Run the tests using the minitest-ci gem.  This will
      # create the test/reports folder.
      - run: bundle exec rake test

      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports