version: 2
jobs:
  build:
    docker:
      # Image to run Ruby 1.9.3 with the latest bundler, RubyGems, etc.
      - image: corgibytes/ruby-1.9.3:1.0.0
        environment:
          TESTOPTS: "--ci-dir=$CIRCLE_TEST_REPORTS/reports"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake test