version: 2
jobs:
  build:
    docker:
      # Image to run Ruby 1.9.3 with the latest bundler, RubyGems, etc.
      - image: corgibytes/ruby-1.9.3:1.0.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Run the tests using the minitest-ci gem.  This will
      # create the test/reports folder.
      - run: bundle exec rake test

      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports


  deploy:
    docker:
      - image: corgibytes/ruby-1.9.3:1.0.0

    working_directory: ~/repo

    steps:
      - checkout

      # Create the RubyGems credential file which as the
      # RubyGems API key in it.  See the sh file for details
      # about the Environment variable that should be setup.
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh

      # Assumes the version number in the version.rb file
      # is the same as the tag.  If not then this will fail.
      - run:
          name: Publish to Rubygems
          command: |
            VERSION=${CIRCLE_TAG/v/''}
            gem build tax_cloud.gemspec
            mkdir artifacts
            cp corgibytes-tax_cloud-$VERSION.gem artifacts
          #gem push corgibytes-tax_cloud-$VERSION.gem

      - store_artifacts:
          path: artifacts

# Do the build on every commit but only do the
# the deploy to RubyGems on tags.  The tag should be
# v#.#.#.  Don't forget to update the version.rb
# file before tagging the build.
workflows:
  version: 2
  test-deploy:
    jobs:
      # By default the tag filter is set to ignore all (i.e. /.*/).
      # This is a problem as deploy depends on build but build
      # won't run on tags by default.  To fix this allow
      # build to run on any tags.
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9.]+/
            branches:
              ignore: /.*/